require: rubocop-rails

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config.ru'
  TargetRubyVersion: 2.6.3

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - 'app/policies/**/*'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - '**/*.jbuilder'

Naming/MethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/ConditionalAssignment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
